### ISSUE TITLE
bug: 窗口模式下捕获位置异常

### ISSUE THREAD

**Issue by TomIsFat** [mumawQAQ/hsr-scanner#1]
经测试，在分辨率：1920x1080 或者 1280x720 窗口下文本捕获异常
全屏工作正常

![image](https://github.com/mumawQAQ/hsr-scanner/assets/76768214/7295eebb-e223-4eea-a66f-4a06e8adad08)

**Comment by mumawQAQ** [comment]
目前版本暂未支持窗口化的识别，暂时可能需要在全屏的情况下使用。
