### ISSUE TITLE
图像捕获失败？

### ISSUE THREAD

**Issue by yimo0908** [mumawQAQ/hsr-scanner#2]
![image](https://github.com/mumawQAQ/hsr-scanner/assets/53830825/56f12b6a-da90-430d-893a-27135da55617)
![image](https://github.com/mumawQAQ/hsr-scanner/assets/53830825/6072779c-92a9-4357-b614-9985660966d6)
按照要求设置了，但捕获的结果不对

**Comment by mumawQAQ** [comment]
是所有的遗器显示都是这样的吗？

**Comment by kroulis** [comment]
我这里也有这个问题
![image](https://github.com/mumawQAQ/hsr-scanner/assets/8529704/9507ac53-f1eb-400c-9d34-9f54eae1574f)

**Comment by kroulis** [comment]
经过debug，console报以下错误：
![image](https://github.com/mumawQAQ/hsr-scanner/assets/8529704/af5a3083-e6b0-44a2-bdb6-9a3d3ca2e831)

**Comment by kroulis** [comment]
经过进一步检查，鉴定为星铁客户端可能阻止了屏幕截取（取句柄无效）。
如果替换为全屏截取，可以正常使用。
![image](https://github.com/mumawQAQ/hsr-scanner/assets/8529704/f90f6e9f-4c7b-45d8-b8d5-cc8a84187425)
![image](https://github.com/mumawQAQ/hsr-scanner/assets/8529704/058d3a64-bf92-4f1b-8d36-b2d29dc4ccb7)

**Comment by 1235789gzy1** [comment]
![image](https://github.com/mumawQAQ/hsr-scanner/assets/52618207/bb9210c1-e66a-4d5e-bcdf-cc539362bae7)

按照要求使用全屏1080p仍无法识别遗器,经测试不支持8:5(2560x1600),但是支持16:9(2560x1440)
