### ISSUE TITLE
关于识别的问题

### ISSUE THREAD

**Issue by landisyu** [mumawQAQ/hsr-scanner#27]
在符合要求的情况下，英文，1080p全屏，存在某些情况可以完全识别，大部分情况ocr无效的情况，具体图片可见
![fbab11b6be71957600b5ecef6932b14f](https://github.com/mumawQAQ/hsr-scanner/assets/44997685/6989c2bc-a26b-4fa4-98d2-04f254624750)
![f6f90048fbf124da75ae413cf100cb5c](https://github.com/mumawQAQ/hsr-scanner/assets/44997685/2dd5cfd5-bd76-464b-94e4-075d63555399)

**Comment by landisyu** [comment]
已测试游戏和工具重启后仍是这样

**Comment by landisyu** [comment]
有没有可能是图片截图后阈值调整导致OCR出现了偏差

**Comment by landisyu** [comment]
但我用1920*1200非全屏测试时候发现ocr识别正常，只是只能截取一半

**Comment by mumawQAQ** [comment]
可能是背景颜色对识别的影响，建议更换游戏环境背景，可以看下面输出画面是否正常。例如图2中，可见周围颜色对数字识别产生了干扰。
