### ISSUE TITLE
Bug:无法识别屏幕比例非16：9得全屏

### ISSUE THREAD

**Issue by 940842546** [mumawQAQ/hsr-scanner#35]
![image](https://github.com/user-attachments/assets/171a9919-6337-4ed1-b55e-9ecdcfc371b3)
游戏已经设置为了1920x1080 fullscreen 但是无法识别 建议添加窗口模式识别
![image](https://github.com/user-attachments/assets/8044837f-a85c-4f2f-8020-da8e9f4be889)

**Comment by mumawQAQ** [comment]
对于屏幕分辨率不是1.77长宽比的，目前暂时解决办法可以把屏幕分辨率设置为1.77，例如1920*1080。下个大版本会支持窗口化以及不同分辨率。
