### ISSUE TITLE
Bug:无法识别屏幕

### ISSUE THREAD

**Issue by Kotagan** [mumawQAQ/hsr-scanner#38]
更新了3.0版本，1920*1080全屏幕依然识别不了，没有1920*1080的窗口模式，显卡已经更新驱动到最新
![image](https://github.com/user-attachments/assets/ce1bc235-d9cc-4418-a6b1-7eca75503582)
![image](https://github.com/user-attachments/assets/451d26cb-ce5f-4631-b381-cd5b706d967d)

**Comment by mumawQAQ** [comment]
要把游戏设置成英语才可以识别
