### ISSUE TITLE
我也看不懂，up

### ISSUE THREAD

**Issue by Kyd-001** [mumawQAQ/hsr-scanner#40]
Error: WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/65/ff/cdae0a8c2118a0de74b6cf4cbcdcaf8fd25857e6c3f205ce4b1794b27814/PyAutoGUI-0.9.54.tar.gz#sha256=dd1d29e8fd118941cb193f74df57e5c6ff8e9253b99c7b04f39cfc69f3ae04b2 (from https://pypi.tuna.tsinghua.edu.cn/simple/pyautogui/). Command errored out with exit status 1: 'D:\Microsoft\HSR-Scanner\resources\tools\python\python.exe' 'D:\Microsoft\HSR-Scanner\resources\tools\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\�����~1\AppData\Local\Temp\tmpv_l7zfsl' Check the logs for full command output.
Error: ERROR: Could not find a version that satisfies the requirement PyAutoGUI==0.9.54 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 0.9.17, 0.9.18, 0.9.19, 0.9.20, 0.9.21, 0.9.22, 0.9.23, 0.9.24, 0.9.25, 0.9.26, 0.9.30, 0.9.31, 0.9.33, 0.9.34, 0.9.35, 0.9.36, 0.9.37, 0.9.38, 0.9.39, 0.9.40, 0.9.41, 0.9.42, 0.9.43, 0.9.44, 0.9.45, 0.9.46, 0.9.47, 0.9.48, 0.9.50, 0.9.51, 0.9.52, 0.9.53, 0.9.54)
Error: ERROR: No matching distribution found for PyAutoGUI==0.9.54
Error: WARNING: You are using pip version 21.1.1; however, version 24.2 is available.
You should consider upgrading via the 'D:\Microsoft\HSR-Scanner\resources\tools\python\python.exe -m pip install --upgrade pip' command.
Failed to install required Python packages.

**Comment by mumawQAQ** [comment]
你路径里有中文吗
