### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by PoemMisty** [mumawQAQ/hsr-scanner#41]
一、安装依赖可以选择不同的源，清华源并不一定稳定，尤其对于南方还是移动的朋友，帮几个朋友安装，都是网络问题
二、建议取消主窗口强制置顶，虽然影响不大
三、适配角色遗器界面，方便升级后可以直接装备

**Comment by mumawQAQ** [comment]
1. 后面会加上上交的源的
2. 这个主要不指定会很麻烦，每次点游戏画面，工具就看不到了
3. 这个后面训练一下角色界面就好了，现在自己做实在是没时间训练模型

**Comment by PoemMistyMoon** [comment]
1
