### ISSUE TITLE
崩铁的遗器词条强化概率好像並不均等

### ISSUE THREAD

**Issue by tom-choi** [mumawQAQ/hsr-scanner#9]
https://nga.178.com/read.php?tid=37079487&rand=309
![image](https://github.com/mumawQAQ/hsr-scanner/assets/58120532/cdefadcf-f2c8-4d9d-a3d9-f41bd247f207)

**Comment by mumawQAQ** [comment]
对的 除此之外 副属性每次升级 加的成长值也不是一样的
